### ISSUE TITLE
Moving objects between OUs?

### ISSUE THREAD

**Issue by dkjajhqu2h3j** [aniqfakhrul/powerview.py#75]
Hi,

Thank you for this tool.

I am currently testing out the attack shown [here](https://www.youtube.com/watch?v=GsTfIAw5WFY) in which the presenter uses a member of the Exchange domain group Exchange Trusted Subsystem to create a new OU, enable inheritance on that then move the Domain Controller OU into the new OU after which it is possible RBCD a DC. I don't think you can move the Domain Controller OU anymore but it is still possible to target individual computers or users as long as they don't have "adminCount" set to "1".

I see that Powerview.py can add OUs and grant yourself GenericAll rights on that. However, I cannot find a way to move an object into the added OU. Is that possible?

**Comment by H0j3n** [comment]
Hi! We already implemented the `Set-DomainObjectDN` module in dev branch. Please verify in your environment if it works as intended. Example command:

```cs
Set-DomainObjectDN -Identity 'CN=DC,OU=Domain Controllers,DC=RANGE,DC=local' -BaseDN 'OU=EvilOU,DC=RANGE,DC=local'
```

**Comment by dkjajhqu2h3j** [comment]
Great. That works! Thanks!

However, it seems using the command `Add-DomainObjectAcl -PrincipalIdentity adlab1_domainuser2 -Rights all -TargetIdentity 'OU=test5,DC=adlab1,DC=local'` does not enable inheritance. After moving an object into the new OU it is still not possible to for example write Shadow credentials on it.

If I use Impacket's dacledit.py (PR 1291) to enable inheritance on the new OU things works. My GenericAll rights are inherited which means I can for example write Shadow credentials.

Here is the DACL of OU test5 after using the `Add-DomainObjectAcl` command above:
![DACL1](https://github.com/aniqfakhrul/powerview.py/assets/153735386/40e46fdf-1128-4671-b621-d27e5c776a3e)

Here is the DACL of OU test5 after enabling inheritance using dacledit.py. As you can see there are differences:
![DACL2](https://github.com/aniqfakhrul/powerview.py/assets/153735386/7fa972df-ea66-4811-876e-aa2204c94cc3)

Is it possible to toggle inheritance using Powerview.py? If yes, how? If not, can that be implemented?

**Comment by dkjajhqu2h3j** [comment]
I checked out the updated Dev branch and tested this again. The parameter `-Inheritance` is now available but either GenericAll rights or inheritance is not set since writing shadow credentials fails. 

Using the command `Add-DomainObjectACL` with the new parameter:
<img width="633" alt="inheritance1" src="https://github.com/aniqfakhrul/powerview.py/assets/153735386/ac655f7b-ef35-47d8-9f30-de6c724c7029">

DACL of OU pentest after the command `Add-DomainObjectACL`:
<img width="695" alt="dacl3" src="https://github.com/aniqfakhrul/powerview.py/assets/153735386/a04584bc-3a4c-4cd5-a751-530c29cacaf9">

To me it seems ACE [10] is missing. See earlier screenshot.

**Comment by H0j3n** [comment]
Hi, thank you for your patience. We have updated the "dev" branch, you may need to pull the latest version.

You can use the same command previously mentioned by @aniqfakhrul:

```cs
Add-DomainObjectAcl -PrincipalIdentity 'CN=Issue75_compr_user,OU=Issue75_OU,DC=RANGE,DC=local' -TargetIdentity 'Issue75_OU' -Rights FullControl -Inheritance
```

After applied:

![image](https://github.com/aniqfakhrul/powerview.py/assets/51261763/36da7cf5-a5c0-4434-aa5b-357fc9a789f1)



Can you please verify is this resolves the issue. Thanks!

**Comment by dkjajhqu2h3j** [comment]
Good work! Now it works. Thank you!

I did however find a small issue. The installation of the current Dev branch fails due to the trailing "´´" on line 2 in requirements.txt. After removing those the installation works.

**Comment by H0j3n** [comment]
Thanks! The issue in `requirements.txt` has been fixed. Appreciate it.
